#spring.application.name=ETEjournal
#
##spring.data.mongodb.database = journalDB
#spring.mongodb.uri=mongodb+srv://prakharshahi9935_db_user:3EHrNfkqH5igW0Rk@cluster0.40nmpfs.mongodb.net/journalDB?appName=Cluster0
#spring.data.mongodb.auto-index-creation=true
##3EHrNfkqH5igW0Rk